### ISSUE TITLE
How do i use it?

### ISSUE THREAD

**Issue by Oricks** [JKAnderson/DSR-Gadget#2]
Sorry this might sound a little but dumb but how do i use this software? the file doesnt have an exe file and im just not sure what to do after downloading

**Comment by JKAnderson** [comment]
Make sure you download the top file from a release on the releases page, not from the main page. The latest one is here:
https://github.com/JKAnderson/DSR-Gadget/releases/download/1.6/DSR.Gadget.1.6.zip
