### ISSUE TITLE
Cant use the mod

### ISSUE THREAD

**Issue by Faldian** [JKAnderson/DSR-Gadget#5]
when i try to open it this shows up 
![image](https://user-images.githubusercontent.com/60578287/73611637-7b36aa80-45ec-11ea-9ef5-1e8ab9b04816.png)
When i dont have the game on it doesnt say that but as soon as i open the game i get an error.
![image](https://user-images.githubusercontent.com/60578287/73611649-90abd480-45ec-11ea-8e11-334aa0154a75.png)

**Comment by Mando131** [comment]
right click > run as administrator
